name: hello

on:
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库文件
        uses: actions/checkout@v7
      - name: 安装 bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.14
      - name: 查看 bun 的版本
        run: bun --version
